version: '3.7'
services:
  metermon-ha:  # Changed container and service name
    image: <YOUR_DOCKERHUB_USERNAME>/metermon-ha:latest  # Use your Docker Hub username
    container_name: metermon-ha  # Changed container name
    environment:
      - MQTT_BROKER_HOST=127.0.0.1  #  Your MQTT broker IP
      - MQTT_BROKER_PORT=1883
      - MQTT_CLIENT_ID=metermon-ha
      - MQTT_USERNAME=metermon       #  Your MQTT username (if needed)
      - MQTT_PASSWORD=<PASSWORD>      #  Your MQTT password (if needed, use secrets)
      - MQTT_TOPIC_PREFIX=metermon-ha  #  Consistent with the script
      - RTL_TCP_SERVER=127.0.0.1:1234 # Your rtlamr instance
      - RTLAMR_MSGTYPE=all
      #- RTLAMR_FILTERID=             # Optional meter ID filter
      - RTLAMR_UNIQUE=true
      - METERMON_ELECTRIC_DIVISOR=100.0
      - METERMON_WATER_DIVISOR=10.0
    restart: unless-stopped
